import type { Partner } from './types'

export const defaultPartners: Partner[] = [
  {
    id: 'osf',
    name: 'Open Society Foundations',
    acronym: 'OSF',
    region: 'Global',
    category: 'FOUNDATION',
    tags: ['Democracy', 'Human Rights', 'Justice'],
    since_year: 2018,
    website_url: 'https://opensocietyfoundations.org',
    logo_url: null,
    display_order: 1,
    is_sub_partner: true,
    parent_partner_id: null,
    created_at: '',
    description:
      'Open Society Foundations builds vibrant and tolerant democracies. OAK partnership covers digital rights and justice initiatives across Eastern Europe and Central Asia.',
    contact_name: 'Maria Schmidt',
    contact_initials: 'MS',
    contact_email: 'm.schmidt@osf.org',
  },
  {
    id: 'aca',
    name: 'Africa Climate Alliance',
    acronym: 'ACA',
    region: 'Sub-Saharan Africa',
    category: 'NGO',
    tags: ['NGO', 'Climate Justice', 'Youth Advocacy'],
    since_year: 2020,
    website_url: 'https://africaclimatealliance.org',
    logo_url: null,
    display_order: 2,
    is_sub_partner: true,
    parent_partner_id: null,
    created_at: '',
    description:
      'Africa Climate Alliance is a youth-led grassroots movement campaigning for transformative climate justice, pan-African ecological action, and community resilience across Sub-Saharan Africa.',
    contact_name: 'Samuel Okafor',
    contact_initials: 'SO',
    contact_email: 's.okafor@africaclimatealliance.org',
  },
  {
    id: 'nec',
    name: 'Nordic Evaluation Centre',
    acronym: 'NEC',
    region: 'Northern Europe',
    category: 'RESEARCH',
    tags: ['Research', 'Evaluation', 'Learning'],
    since_year: 2021,
    website_url: 'https://nordicevaluation.org',
    logo_url: null,
    display_order: 3,
    is_sub_partner: true,
    parent_partner_id: null,
    created_at: '',
    description:
      'Nordic Evaluation Centre provides participatory evaluation methodology, systemic metrics, and institutional learning frameworks for philanthropic partnerships.',
    contact_name: 'Dr. Ingrid Holm',
    contact_initials: 'IH',
    contact_email: 'i.holm@nordicevaluation.org',
  },
  {
    id: 'mrg',
    name: 'MENA Rights Group',
    acronym: 'MRG',
    region: 'Middle East & North Africa',
    category: 'NGO',
    tags: ['NGO', 'Human Rights', 'Documentation'],
    since_year: 2019,
    website_url: 'https://menarights.org',
    logo_url: null,
    display_order: 4,
    is_sub_partner: false,
    parent_partner_id: null,
    created_at: '',
    description:
      'Geneva-based legal advocacy NGO dedicated to defending fundamental rights and documenting violations across the Middle East and North Africa through UN mechanisms.',
    contact_name: 'Fatima Zahra Benali',
    contact_initials: 'FB',
    contact_email: 'f.benali@menarights.org',
  },
  {
    id: 'dfi',
    name: 'Digital Frontiers Institute',
    acronym: 'DFI',
    region: 'Global / East Africa',
    category: 'RESEARCH',
    tags: ['Research', 'Digital Rights', 'Internet Freedom'],
    since_year: 2022,
    website_url: 'https://digitalfrontiers.org',
    logo_url: null,
    display_order: 5,
    is_sub_partner: false,
    parent_partner_id: null,
    created_at: '',
    description:
      'Digital Frontiers Institute conducts applied research and capacity building to defend internet freedom, cryptographic security, and data privacy in restrictive environments.',
    contact_name: 'Li Wei',
    contact_initials: 'LW',
    contact_email: 'l.wei@digitalfrontiers.org',
  },
  {
    id: 'gal',
    name: 'Global Advocacy Lab',
    acronym: 'GAL',
    region: 'Global',
    category: 'NGO',
    tags: ['NGO', 'Communications', 'Campaigns'],
    since_year: 2023,
    website_url: 'https://globaladvocacylab.org',
    logo_url: null,
    display_order: 6,
    is_sub_partner: false,
    parent_partner_id: null,
    created_at: '',
    description:
      'Specialized campaign and communications accelerator collaborating with grassroots movements to elevate frontline voices and influence policy reform.',
    contact_name: 'Amara Diallo',
    contact_initials: 'AD',
    contact_email: 'a.diallo@globaladvocacylab.org',
  },
  {
    id: 'sp',
    name: 'Sciences Po Paris',
    acronym: 'SP',
    region: 'Western Europe',
    category: 'ACADEMIC',
    tags: ['Academic', 'Research', 'Policy'],
    since_year: 2020,
    website_url: 'https://sciencespo.fr',
    logo_url: null,
    display_order: 7,
    is_sub_partner: false,
    parent_partner_id: null,
    created_at: '',
    description:
      'Premier international research university specializing in political science, international relations, sustainable development, and public governance.',
    contact_name: 'Prof. Jean-Luc Mercier',
    contact_initials: 'JM',
    contact_email: 'jl.mercier@sciencespo.fr',
  },
  {
    id: 'efg',
    name: 'Environmental Funders Group',
    acronym: 'EFG',
    region: 'Europe',
    category: 'NETWORK',
    tags: ['Network', 'Environment', 'Climate'],
    since_year: 2017,
    website_url: 'https://envfunders.eu',
    logo_url: null,
    display_order: 8,
    is_sub_partner: false,
    parent_partner_id: null,
    created_at: '',
    description:
      'Collaborative philanthropic network of European trusts and foundations pooling resources to tackle biodiversity loss, climate breakdown, and environmental inequality.',
    contact_name: 'Claire Van Der Bilt',
    contact_initials: 'CB',
    contact_email: 'c.vanderbilt@envfunders.eu',
  },
]

export function getPartnerById(id: string): Partner | undefined {
  const normalizedId = id.toLowerCase()
  return (
    defaultPartners.find(
      (p) =>
        p.id.toLowerCase() === normalizedId ||
        p.acronym?.toLowerCase() === normalizedId ||
        p.name.toLowerCase().replace(/\s+/g, '-') === normalizedId
    ) || defaultPartners[0]
  )
}
